package com.example.proyectoaplicacionlenguajesignos;

import com.example.proyectoaplicacionlenguajesignos.models.Palabra;

import java.util.ArrayList;
import java.util.List;

import io.realm.Realm;

public class Utils {
    public List<Palabra> rellenar(){
        List list = new ArrayList();
        list.add(new Palabra("Alfombra",R.drawable.alfombra,"Casa","Casa"));
        list.add(new Palabra("Armario",R.drawable.armario,"Casa","Casa"));
        list.add(new Palabra("Baño",R.drawable.bano,"Casa","Casa"));
        list.add(new Palabra("Cama",R.drawable.cama,"Casa","Casa"));
        list.add(new Palabra("Casa",R.drawable.casa,"Casa","Casa"));
        list.add(new Palabra("Cocina",R.drawable.cocina,"Casa","Casa"));
        list.add(new Palabra("Cristal",R.drawable.cristal,"Casa","Casa"));
        list.add(new Palabra("Despertador",R.drawable.despertador,"Casa","Casa"));
        list.add(new Palabra("Dormitorio",R.drawable.dormitorio,"Casa","Casa"));
        list.add(new Palabra("Lámpara",R.drawable.lampara,"Casa","Casa"));
        list.add(new Palabra("Maceta",R.drawable.maceta,"Casa","Casa"));
        list.add(new Palabra("Manta",R.drawable.manta,"Casa","Casa"));
        list.add(new Palabra("Máquina",R.drawable.maquina,"Casa","Casa"));
        list.add(new Palabra("Mesilla",R.drawable.mesilla,"Casa","Casa"));
        list.add(new Palabra("Mueble",R.drawable.mueble,"Casa","Casa"));
        list.add(new Palabra("Muñeco",R.drawable.muneco,"Casa","Casa"));
        list.add(new Palabra("Objeto",R.drawable.objeto,"Casa","Casa"));
        list.add(new Palabra("Pelota",R.drawable.pelota,"Casa","Casa"));
        list.add(new Palabra("Plancha",R.drawable.plancha,"Casa","Casa"));
        list.add(new Palabra("Puerta",R.drawable.puerta,"Casa","Casa"));
        list.add(new Palabra("Sábana",R.drawable.sabana,"Casa","Casa"));
        list.add(new Palabra("Salón",R.drawable.salon,"Casa","Casa"));
        list.add(new Palabra("Silla",R.drawable.silla,"Casa","Casa"));
        list.add(new Palabra("Sofá",R.drawable.sofa,"Casa","Casa"));
        list.add(new Palabra("Teléfono",R.drawable.telefono,"Casa","Casa"));
        list.add(new Palabra("Televisor",R.drawable.televisor,"Casa","Casa"));
        list.add(new Palabra("Ventana",R.drawable.ventana,"Casa","Casa"));
        list.add(new Palabra("Video",R.drawable.video,"Casa","Casa"));

        list.add(new Palabra("Cacerola",R.drawable.cacerola,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Cocina",R.drawable.cocina,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Cuchara",R.drawable.cuchara,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Cuchillo",R.drawable.cuchillo,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Jarra",R.drawable.jarra,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Lavadora",R.drawable.lavadora,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Nevera",R.drawable.nevera,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Objetos",R.drawable.objetos,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Plato",R.drawable.plato,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Sartén",R.drawable.sarten,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Servilleta",R.drawable.servilleta,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Tenedor",R.drawable.tenedor,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Vaso",R.drawable.vaso,"Casa","ObjetosDeCocina"));

        list.add(new Palabra("Bañera",R.drawable.banera,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Cepillo",R.drawable.cepillo,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Champú",R.drawable.champu,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Colonia",R.drawable.colonia,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Espejo",R.drawable.espejo,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Esponja",R.drawable.esponja,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Jabón",R.drawable.jabon,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Lavabo",R.drawable.lavabo,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Objetos",R.drawable.objetos,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Papel",R.drawable.papel,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Pasta de dientes",R.drawable.pasta_de_dientes,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Peine",R.drawable.peine,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Toalla",R.drawable.toalla,"Casa","ObjetosDeBaño"));

        list.add(new Palabra("Acera",R.drawable.acera,"Ciudad","Ciudad"));
        list.add(new Palabra("Banco (Dinero)",R.drawable.banco_dinero,"Ciudad","Ciudad"));
        list.add(new Palabra("Banco (Sentarse)",R.drawable.banco_sentar,"Ciudad","Ciudad"));
        list.add(new Palabra("Biblioteca",R.drawable.biblioteca,"Ciudad","Ciudad"));
        list.add(new Palabra("Buzón",R.drawable.buzon,"Ciudad","Ciudad"));
        list.add(new Palabra("Calle",R.drawable.calle,"Ciudad","Ciudad"));
        list.add(new Palabra("Cine",R.drawable.cine,"Ciudad","Ciudad"));
        list.add(new Palabra("Ciudad",R.drawable.ciudad,"Ciudad","Ciudad"));
        list.add(new Palabra("Colegio",R.drawable.colegio,"Ciudad","Ciudad"));
        list.add(new Palabra("Columpio",R.drawable.columpio,"Ciudad","Ciudad"));
        list.add(new Palabra("Farola",R.drawable.farola,"Ciudad","Ciudad"));
        list.add(new Palabra("Fuente",R.drawable.fuente,"Ciudad","Ciudad"));
        list.add(new Palabra("Hospital",R.drawable.hospital,"Ciudad","Ciudad"));
        list.add(new Palabra("Librería",R.drawable.libreria,"Ciudad","Ciudad"));
        list.add(new Palabra("Luz",R.drawable.luz,"Ciudad","Ciudad"));
        list.add(new Palabra("Museo",R.drawable.museo,"Ciudad","Ciudad"));
        list.add(new Palabra("Parque",R.drawable.parque,"Ciudad","Ciudad"));
        list.add(new Palabra("Paso de cebra",R.drawable.paso_de_cebra,"Ciudad","Ciudad"));
        list.add(new Palabra("Pastelería",R.drawable.pasteleria,"Ciudad","Ciudad"));
        list.add(new Palabra("Plaza",R.drawable.plaza,"Ciudad","Ciudad"));
        list.add(new Palabra("Puente",R.drawable.puente,"Ciudad","Ciudad"));
        list.add(new Palabra("Quiosco",R.drawable.quiosco,"Ciudad","Ciudad"));
        list.add(new Palabra("Semáforo",R.drawable.semaforo,"Ciudad","Ciudad"));
        list.add(new Palabra("Supermercado",R.drawable.supermercado,"Ciudad","Ciudad"));
        list.add(new Palabra("Teatro",R.drawable.teatro,"Ciudad","Ciudad"));
        list.add(new Palabra("Tienda",R.drawable.tienda,"Ciudad","Ciudad"));
        list.add(new Palabra("Tobogán",R.drawable.tobogan,"Ciudad","Ciudad"));
        list.add(new Palabra("Zapatería",R.drawable.zapateria,"Ciudad","Ciudad"));

        list.add(new Palabra("Ambulancia",R.drawable.ambulancia,"Ciudad","MediosDeTransporte"));
        list.add(new Palabra("Autobús",R.drawable.autobus,"Ciudad","MediosDeTransporte"));
        list.add(new Palabra("Barca",R.drawable.barca,"Ciudad","MediosDeTransporte"));
        list.add(new Palabra("Bicicleta",R.drawable.bicicleta,"Ciudad","MediosDeTransporte"));
        list.add(new Palabra("Camión",R.drawable.camion,"Ciudad","MediosDeTransporte"));
        list.add(new Palabra("Coche",R.drawable.coche,"Ciudad","MediosDeTransporte"));
        list.add(new Palabra("Moto",R.drawable.moto,"Ciudad","MediosDeTransporte"));
        list.add(new Palabra("Vehículo",R.drawable.vehiculo,"Ciudad","MediosDeTransporte"));

        list.add(new Palabra("Bombero",R.drawable.bombero,"Ciudad","Profesiones"));
        list.add(new Palabra("Médico",R.drawable.medico,"Ciudad","Profesiones"));
        list.add(new Palabra("Pastelero",R.drawable.pastelero,"Ciudad","Profesiones"));
        list.add(new Palabra("Pescador",R.drawable.pescador,"Ciudad","Profesiones"));
        list.add(new Palabra("Policía",R.drawable.policia,"Ciudad","Profesiones"));
        list.add(new Palabra("Profesiones",R.drawable.profesiones,"Ciudad","Profesiones"));
        list.add(new Palabra("Profesor",R.drawable.profesor,"Ciudad","Profesiones"));
        list.add(new Palabra("Transporte",R.drawable.transporte,"Ciudad","Profesiones"));

        list.add(new Palabra("Abecedario",R.drawable.abecedario,"Colegio","Colegio"));
        list.add(new Palabra("Alumno",R.drawable.alumno,"Colegio","Colegio"));
        list.add(new Palabra("Clase",R.drawable.clase,"Colegio","Colegio"));
        list.add(new Palabra("Colegio",R.drawable.colegio,"Colegio","Colegio"));
        list.add(new Palabra("Dibujo",R.drawable.dibujo,"Colegio","Colegio"));
        list.add(new Palabra("Diferencia",R.drawable.diferencia,"Colegio","Colegio"));
        list.add(new Palabra("Gramo",R.drawable.gramo,"Colegio","Colegio"));
        list.add(new Palabra("Lenguaje De Signos español",R.drawable.lenguajessignosespa_ola,"Colegio","Colegio"));
        list.add(new Palabra("Litro",R.drawable.litro,"Colegio","Colegio"));
        list.add(new Palabra("Medida",R.drawable.medida,"Colegio","Colegio"));
        list.add(new Palabra("Metro",R.drawable.metro,"Colegio","Colegio"));
        list.add(new Palabra("Multiplicación",R.drawable.multiplicacion,"Colegio","Colegio"));
        list.add(new Palabra("Número",R.drawable.numero,"Colegio","Colegio"));
        list.add(new Palabra("Palabra",R.drawable.palabra,"Colegio","Colegio"));
        list.add(new Palabra("Patio",R.drawable.patio,"Colegio","Colegio"));
        list.add(new Palabra("Resta",R.drawable.resta,"Colegio","Colegio"));
        list.add(new Palabra("Servicio",R.drawable.servicio,"Colegio","Colegio"));
        list.add(new Palabra("Suma",R.drawable.suma,"Colegio","Colegio"));

        list.add(new Palabra("Amarillo",R.drawable.amarillo,"Colegio","Colores"));
        list.add(new Palabra("Azul",R.drawable.azul,"Colegio","Colores"));
        list.add(new Palabra("Blanco",R.drawable.blanco,"Colegio","Colores"));
        list.add(new Palabra("Colores",R.drawable.colores,"Colegio","Colores"));
        list.add(new Palabra("Marrón",R.drawable.marron,"Colegio","Colores"));
        list.add(new Palabra("Naranja",R.drawable.naranja,"Colegio","Colores"));
        list.add(new Palabra("Negro",R.drawable.negro,"Colegio","Colores"));
        list.add(new Palabra("Rojo",R.drawable.rojo,"Colegio","Colores"));
        list.add(new Palabra("Rosa",R.drawable.rosa,"Colegio","Colores"));
        list.add(new Palabra("Verde",R.drawable.verde,"Colegio","Colores"));

        list.add(new Palabra("Bolígrafo",R.drawable.boligrafo,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Borrador",R.drawable.borrador,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Cera",R.drawable.cera,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Cosas del colegio",R.drawable.cosas_del_colegio,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Cosas",R.drawable.cosas,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Cuaderno",R.drawable.cuaderno,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Cuento",R.drawable.cuento,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Diccionario",R.drawable.diccionario,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Goma",R.drawable.goma,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Hoja",R.drawable.hoja,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Lápices de colores",R.drawable.lapices_de_colores,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Lápiz",R.drawable.lapiz,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Libro",R.drawable.libro,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Papel",R.drawable.papel,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Papelera",R.drawable.papelera,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Pegamento",R.drawable.pegamento,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Pintura",R.drawable.pintura,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Pizarra",R.drawable.pizarra,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Plastilina",R.drawable.plastilina,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Rotulador",R.drawable.rotulador,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Sacapuntas",R.drawable.sacapuntas,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Tijeras",R.drawable.tijeras,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Tiza",R.drawable.tiza,"Colegio","CosasDelColegio"));

        list.add(new Palabra("Círculo",R.drawable.circulo,"Colegio","FormasYTamaños"));
        list.add(new Palabra("Cuadrado",R.drawable.cuadrado,"Colegio","FormasYTamaños"));
        list.add(new Palabra("Formas y Tamaños",R.drawable.formas_y_tamanos,"Colegio","FormasYTamaños"));
        list.add(new Palabra("Formas",R.drawable.formas,"Colegio","FormasYTamaños"));
        list.add(new Palabra("Grande",R.drawable.grande,"Colegio","FormasYTamaños"));
        list.add(new Palabra("Mediano",R.drawable.mediano,"Colegio","FormasYTamaños"));
        list.add(new Palabra("Pequeño",R.drawable.pequeno,"Colegio","FormasYTamaños"));
        list.add(new Palabra("Tamaño",R.drawable.tamano,"Colegio","FormasYTamaños"));

        list.add(new Palabra("Aceite",R.drawable.aceite,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Alimento",R.drawable.alimento,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Arroz",R.drawable.arroz,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Azucar",R.drawable.azucar,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Bebida",R.drawable.bebida,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Bocadillo",R.drawable.bocadillo,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Caramelo",R.drawable.caramelo,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Carnes",R.drawable.carnes,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Cebolla",R.drawable.cebolla,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Cena",R.drawable.cena,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Chocolate",R.drawable.chocolate,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Comida",R.drawable.comida,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Desayuno",R.drawable.desayuno,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Galleta",R.drawable.galleta,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Huevo",R.drawable.huevo,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Leche",R.drawable.leche,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Lechuga",R.drawable.lechuga,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Limón",R.drawable.limon,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Macarrones",R.drawable.macarrones,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Merienda",R.drawable.merienda,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Pan",R.drawable.pan,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Patata",R.drawable.patata,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Pescado",R.drawable.pescado,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Pollo",R.drawable.pollo,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Puré",R.drawable.pure,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Queso",R.drawable.queso,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Sal",R.drawable.sal,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Sed",R.drawable.sed,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Sopa",R.drawable.sopa,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Tomate",R.drawable.tomate,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Zanahoria",R.drawable.zanahoria,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Zumo",R.drawable.zumo,"Comidas Y Bebidas","Comidas Y Bebidas"));

        list.add(new Palabra("Dulce",R.drawable.dulce,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Flan",R.drawable.flan,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Fresa",R.drawable.fresa,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Fruta",R.drawable.fruta,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Helado",R.drawable.helado,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Manzana",R.drawable.manzana,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Naranja",R.drawable.naranja,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Pera",R.drawable.pera,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Platano",R.drawable.platano,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Postre",R.drawable.postre,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Sandía",R.drawable.sandia,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Tarta",R.drawable.tarta,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Uva",R.drawable.uva,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Yogur",R.drawable.yogur,"Comidas Y Bebidas","Postres"));

        list.add(new Palabra("Abuelo",R.drawable.abuelo,"Familia","Familia"));
        list.add(new Palabra("Amigo",R.drawable.amigo,"Familia","Familia"));
        list.add(new Palabra("Bebé",R.drawable.bebe,"Familia","Familia"));
        list.add(new Palabra("Ciego",R.drawable.ciego,"Familia","Familia"));
        list.add(new Palabra("Familia",R.drawable.familia,"Familia","Familia"));
        list.add(new Palabra("Hermano",R.drawable.hermano,"Familia","Familia"));
        list.add(new Palabra("Mamá",R.drawable.mama,"Familia","Familia"));
        list.add(new Palabra("Niña",R.drawable.nina,"Familia","Familia"));
        list.add(new Palabra("Niño",R.drawable.nino,"Familia","Familia"));
        list.add(new Palabra("Papá",R.drawable.papa,"Familia","Familia"));
        list.add(new Palabra("Persona",R.drawable.persona,"Familia","Familia"));
        list.add(new Palabra("Primo",R.drawable.primo,"Familia","Familia"));
        list.add(new Palabra("Sordo",R.drawable.sordo,"Familia","Familia"));
        list.add(new Palabra("Sordo ciego",R.drawable.sordociego,"Familia","Familia"));
        list.add(new Palabra("Tío",R.drawable.tio,"Familia","Familia"));

        list.add(new Palabra("Abeja",R.drawable.abeja,"Naturaleza","Animales"));
        list.add(new Palabra("Águila",R.drawable.aguila,"Naturaleza","Animales"));
        list.add(new Palabra("Animal",R.drawable.animal,"Naturaleza","Animales"));
        list.add(new Palabra("Ballena",R.drawable.ballena,"Naturaleza","Animales"));
        list.add(new Palabra("Burro",R.drawable.burro,"Naturaleza","Animales"));
        list.add(new Palabra("Caballo",R.drawable.caballo,"Naturaleza","Animales"));
        list.add(new Palabra("Cabra",R.drawable.cabra,"Naturaleza","Animales"));
        list.add(new Palabra("Camello",R.drawable.camello,"Naturaleza","Animales"));
        list.add(new Palabra("Cerdo",R.drawable.cerdo,"Naturaleza","Animales"));
        list.add(new Palabra("Cocodrilo",R.drawable.cocodrilo,"Naturaleza","Animales"));
        list.add(new Palabra("Conejo",R.drawable.conejo,"Naturaleza","Animales"));
        list.add(new Palabra("Delfín",R.drawable.delfin,"Naturaleza","Animales"));
        list.add(new Palabra("Elefante",R.drawable.elefante,"Naturaleza","Animales"));
        list.add(new Palabra("Foca",R.drawable.foca,"Naturaleza","Animales"));
        list.add(new Palabra("Gallina",R.drawable.gallina,"Naturaleza","Animales"));
        list.add(new Palabra("Gato",R.drawable.gato,"Naturaleza","Animales"));
        list.add(new Palabra("Granja",R.drawable.granja,"Naturaleza","Animales"));
        list.add(new Palabra("Jirafa",R.drawable.jirafa,"Naturaleza","Animales"));
        list.add(new Palabra("León",R.drawable.leon,"Naturaleza","Animales"));
        list.add(new Palabra("Loro",R.drawable.loro,"Naturaleza","Animales"));
        list.add(new Palabra("Mariposa",R.drawable.mariposa,"Naturaleza","Animales"));
        list.add(new Palabra("Mono",R.drawable.mono,"Naturaleza","Animales"));

        list.add(new Palabra("Abeto",R.drawable.abeto,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Árbol",R.drawable.arbol,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Arcoíris",R.drawable.arco_iris,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Arena",R.drawable.arena,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Estrella",R.drawable.estrella,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Faro",R.drawable.faro,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Flor",R.drawable.flor,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Flotador",R.drawable.flotador,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Fuego",R.drawable.fuego,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Hierba",R.drawable.hierba,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Hoja",R.drawable.hoja,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Lago",R.drawable.lago,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Luna",R.drawable.luna,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Mar",R.drawable.mar,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Margarita",R.drawable.margarita,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Montaña",R.drawable.montana,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Naturaleza",R.drawable.naturaleza,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Palmera",R.drawable.palmera,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Piedra",R.drawable.piedra,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Playa",R.drawable.playa,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Pozo",R.drawable.pozo,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Río",R.drawable.rio,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Saco de dormir",R.drawable.saco_de_dormir,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Sombrilla",R.drawable.sombrilla,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Tienda de campaña",R.drawable.tienda_campana,"Naturaleza","Naturaleza"));

        list.add(new Palabra("Calor",R.drawable.calor,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Frío",R.drawable.frio,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Lluvia",R.drawable.lluvia,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Nieve",R.drawable.nieve,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Nube",R.drawable.nube,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Nublado",R.drawable.nublado,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Sol",R.drawable.sol,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Tiempo atmosfético",R.drawable.tiempo_atmosferico,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Tormenta",R.drawable.tormenta,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Viento",R.drawable.viento,"Naturaleza","TiempoAtmosferico"));

        list.add(new Palabra("Día de la semana",R.drawable.dia_de_la_semana,"Calendario","Semana"));
        list.add(new Palabra("Día",R.drawable.dia_manana,"Calendario","Semana"));
        list.add(new Palabra("Domingo",R.drawable.domingo,"Calendario","Semana"));
        list.add(new Palabra("Fin de semana",R.drawable.fin_de_semana,"Calendario","Semana"));
        list.add(new Palabra("Jueves",R.drawable.jueves,"Calendario","Semana"));
        list.add(new Palabra("Martes",R.drawable.martes,"Calendario","Semana"));
        list.add(new Palabra("Miercoles",R.drawable.miercoles,"Calendario","Semana"));
        list.add(new Palabra("Sabado",R.drawable.sabado,"Calendario","Semana"));
        list.add(new Palabra("Semana",R.drawable.semana,"Calendario","Semana"));
        list.add(new Palabra("Viernes",R.drawable.viernes,"Calendario","Semana"));

        list.add(new Palabra("Estaciones",R.drawable.estaciones,"Calendario","Estaciones"));
        list.add(new Palabra("Invierno",R.drawable.invierno,"Calendario","Estaciones"));
        list.add(new Palabra("Otoño",R.drawable.otono,"Calendario","Estaciones"));
        list.add(new Palabra("Primavera",R.drawable.primavera,"Calendario","Estaciones"));
        list.add(new Palabra("Verano",R.drawable.verano,"Calendario","Estaciones"));

        list.add(new Palabra("Boca",R.drawable.boca,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Brazo",R.drawable.brazo,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Cabeza",R.drawable.cabeza,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Cuerpo",R.drawable.cuerpo,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Culo",R.drawable.culo,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Dedo",R.drawable.dedo,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Dientes",R.drawable.dientes,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Lengua",R.drawable.lengua,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Mano",R.drawable.mano,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Nariz",R.drawable.nariz,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Ojo",R.drawable.ojo,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Oreja",R.drawable.oreja,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Pelo",R.drawable.pelo,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Pene",R.drawable.pene,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Pie",R.drawable.pie,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Pierna",R.drawable.pierna,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Vulva",R.drawable.vulva,"Cuerpo","Cuerpo"));

        list.add(new Palabra("Sentidos",R.drawable.sentidos,"Cuerpo","Sentido"));
        list.add(new Palabra("Gusto",R.drawable.gusto,"Cuerpo","Sentido"));
        list.add(new Palabra("Oido",R.drawable.oido,"Cuerpo","Sentido"));
        list.add(new Palabra("Olfato",R.drawable.olfato,"Cuerpo","Sentido"));
        list.add(new Palabra("Tacto",R.drawable.tacto,"Cuerpo","Sentido"));
        list.add(new Palabra("Vista",R.drawable.vista,"Cuerpo","Sentido"));
        return list;
    }
}
