package com.example.proyectoaplicacionlenguajesignos;

import com.example.proyectoaplicacionlenguajesignos.models.Palabra;

import java.util.ArrayList;
import java.util.List;

import io.realm.Realm;

public class Utils {
    public List<Palabra> rellenar(){
        List list = new ArrayList();
        list.add(new Palabra("Alfombra",R.drawable.alfombra,"Casa","Casa"));
        list.add(new Palabra("Armario",R.drawable.armario,"Casa","Casa"));
        list.add(new Palabra("Baño",R.drawable.bano,"Casa","Casa"));
        list.add(new Palabra("Cama",R.drawable.cama,"Casa","Casa"));
        list.add(new Palabra("Casa",R.drawable.casa,"Casa","Casa"));
        list.add(new Palabra("Cocina",R.drawable.cocina,"Casa","Casa"));
        list.add(new Palabra("Cristal",R.drawable.cristal,"Casa","Casa"));
        list.add(new Palabra("Despertador",R.drawable.despertador,"Casa","Casa"));
        list.add(new Palabra("Dormitorio",R.drawable.dormitorio,"Casa","Casa"));
        list.add(new Palabra("Lámpara",R.drawable.lampara,"Casa","Casa"));
        list.add(new Palabra("Maceta",R.drawable.maceta,"Casa","Casa"));
        list.add(new Palabra("Manta",R.drawable.manta,"Casa","Casa"));
        list.add(new Palabra("Máquina",R.drawable.maquina,"Casa","Casa"));
        list.add(new Palabra("Mesilla",R.drawable.mesilla,"Casa","Casa"));
        list.add(new Palabra("Mueble",R.drawable.mueble,"Casa","Casa"));
        list.add(new Palabra("Muñeco",R.drawable.muneco,"Casa","Casa"));
        list.add(new Palabra("Objeto",R.drawable.objeto,"Casa","Casa"));
        list.add(new Palabra("Pelota",R.drawable.pelota,"Casa","Casa"));
        list.add(new Palabra("Plancha",R.drawable.plancha,"Casa","Casa"));
        list.add(new Palabra("Puerta",R.drawable.puerta,"Casa","Casa"));
        list.add(new Palabra("Sábana",R.drawable.sabana,"Casa","Casa"));
        list.add(new Palabra("Salón",R.drawable.salon,"Casa","Casa"));
        list.add(new Palabra("Silla",R.drawable.silla,"Casa","Casa"));
        list.add(new Palabra("Sofá",R.drawable.sofa,"Casa","Casa"));
        list.add(new Palabra("Teléfono",R.drawable.telefono,"Casa","Casa"));
        list.add(new Palabra("Televisor",R.drawable.televisor,"Casa","Casa"));
        list.add(new Palabra("Ventana",R.drawable.ventana,"Casa","Casa"));
        list.add(new Palabra("Video",R.drawable.video,"Casa","Casa"));

        list.add(new Palabra("Cacerola",R.drawable.cacerola,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Cocina",R.drawable.cocina,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Cuchara",R.drawable.cuchara,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Cuchillo",R.drawable.cuchillo,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Jarra",R.drawable.jarra,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Lavadora",R.drawable.lavadora,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Nevera",R.drawable.nevera,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Objetos",R.drawable.objetos,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Plato",R.drawable.plato,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Sartén",R.drawable.sarten,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Servilleta",R.drawable.servilleta,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Tenedor",R.drawable.tenedor,"Casa","ObjetosDeCocina"));
        list.add(new Palabra("Vaso",R.drawable.vaso,"Casa","ObjetosDeCocina"));

        list.add(new Palabra("Bañera",R.drawable.banera,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Cepillo",R.drawable.cepillo,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Champú",R.drawable.champu,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Colonia",R.drawable.colonia,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Espejo",R.drawable.espejo,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Esponja",R.drawable.esponja,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Jabón",R.drawable.jabon,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Lavabo",R.drawable.lavabo,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Objetos",R.drawable.objetos,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Papel",R.drawable.papel,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Pasta de dientes",R.drawable.pasta_de_dientes,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Peine",R.drawable.peine,"Casa","ObjetosDeBaño"));
        list.add(new Palabra("Toalla",R.drawable.toalla,"Casa","ObjetosDeBaño"));

        list.add(new Palabra("Acera",R.drawable.acera,"Ciudad","Ciudad"));
        list.add(new Palabra("Banco (Dinero)",R.drawable.banco_dinero,"Ciudad","Ciudad"));
        list.add(new Palabra("Banco (Sentarse)",R.drawable.banco_sentar,"Ciudad","Ciudad"));
        list.add(new Palabra("Biblioteca",R.drawable.biblioteca,"Ciudad","Ciudad"));
        list.add(new Palabra("Buzón",R.drawable.buzon,"Ciudad","Ciudad"));
        list.add(new Palabra("Calle",R.drawable.calle,"Ciudad","Ciudad"));
        list.add(new Palabra("Cine",R.drawable.cine,"Ciudad","Ciudad"));
        list.add(new Palabra("Ciudad",R.drawable.ciudad,"Ciudad","Ciudad"));
        list.add(new Palabra("Colegio",R.drawable.colegio,"Ciudad","Ciudad"));
        list.add(new Palabra("Columpio",R.drawable.columpio,"Ciudad","Ciudad"));
        list.add(new Palabra("Farola",R.drawable.farola,"Ciudad","Ciudad"));
        list.add(new Palabra("Fuente",R.drawable.fuente,"Ciudad","Ciudad"));
        list.add(new Palabra("Hospital",R.drawable.hospital,"Ciudad","Ciudad"));
        list.add(new Palabra("Librería",R.drawable.libreria,"Ciudad","Ciudad"));
        list.add(new Palabra("Luz",R.drawable.luz,"Ciudad","Ciudad"));
        list.add(new Palabra("Museo",R.drawable.museo,"Ciudad","Ciudad"));
        list.add(new Palabra("Parque",R.drawable.parque,"Ciudad","Ciudad"));
        list.add(new Palabra("Paso de cebra",R.drawable.paso_de_cebra,"Ciudad","Ciudad"));
        list.add(new Palabra("Pastelería",R.drawable.pasteleria,"Ciudad","Ciudad"));
        list.add(new Palabra("Plaza",R.drawable.plaza,"Ciudad","Ciudad"));
        list.add(new Palabra("Puente",R.drawable.puente,"Ciudad","Ciudad"));
        list.add(new Palabra("Quiosco",R.drawable.quiosco,"Ciudad","Ciudad"));
        list.add(new Palabra("Semáforo",R.drawable.semaforo,"Ciudad","Ciudad"));
        list.add(new Palabra("Supermercado",R.drawable.supermercado,"Ciudad","Ciudad"));
        list.add(new Palabra("Teatro",R.drawable.teatro,"Ciudad","Ciudad"));
        list.add(new Palabra("Tienda",R.drawable.tienda,"Ciudad","Ciudad"));
        list.add(new Palabra("Tobogán",R.drawable.tobogan,"Ciudad","Ciudad"));
        list.add(new Palabra("Zapatería",R.drawable.zapateria,"Ciudad","Ciudad"));

        list.add(new Palabra("Ambulancia",R.drawable.ambulancia,"Ciudad","MediosDeTransporte"));
        list.add(new Palabra("Autobús",R.drawable.autobus,"Ciudad","MediosDeTransporte"));
        list.add(new Palabra("Barca",R.drawable.barca,"Ciudad","MediosDeTransporte"));
        list.add(new Palabra("Bicicleta",R.drawable.bicicleta,"Ciudad","MediosDeTransporte"));
        list.add(new Palabra("Camión",R.drawable.camion,"Ciudad","MediosDeTransporte"));
        list.add(new Palabra("Coche",R.drawable.coche,"Ciudad","MediosDeTransporte"));
        list.add(new Palabra("Moto",R.drawable.moto,"Ciudad","MediosDeTransporte"));
        list.add(new Palabra("Vehículo",R.drawable.vehiculo,"Ciudad","MediosDeTransporte"));

        list.add(new Palabra("Bombero",R.drawable.bombero,"Ciudad","Profesiones"));
        list.add(new Palabra("Médico",R.drawable.medico,"Ciudad","Profesiones"));
        list.add(new Palabra("Pastelero",R.drawable.pastelero,"Ciudad","Profesiones"));
        list.add(new Palabra("Pescador",R.drawable.pescador,"Ciudad","Profesiones"));
        list.add(new Palabra("Policía",R.drawable.policia,"Ciudad","Profesiones"));
        list.add(new Palabra("Profesiones",R.drawable.profesiones,"Ciudad","Profesiones"));
        list.add(new Palabra("Profesor",R.drawable.profesor,"Ciudad","Profesiones"));
        list.add(new Palabra("Transporte",R.drawable.transporte,"Ciudad","Profesiones"));

        list.add(new Palabra("Abecedario",R.drawable.abecedario,"Colegio","Colegio"));
        list.add(new Palabra("Alumno",R.drawable.alumno,"Colegio","Colegio"));
        list.add(new Palabra("Clase",R.drawable.clase,"Colegio","Colegio"));
        list.add(new Palabra("Colegio",R.drawable.colegio,"Colegio","Colegio"));
        list.add(new Palabra("Dibujo",R.drawable.dibujo,"Colegio","Colegio"));
        list.add(new Palabra("Diferencia",R.drawable.diferencia,"Colegio","Colegio"));
        list.add(new Palabra("Gramo",R.drawable.gramo,"Colegio","Colegio"));
        list.add(new Palabra("Lenguaje De Signos español",R.drawable.lenguajessignosespa_ola,"Colegio","Colegio"));
        list.add(new Palabra("Litro",R.drawable.litro,"Colegio","Colegio"));
        list.add(new Palabra("Medida",R.drawable.medida,"Colegio","Colegio"));
        list.add(new Palabra("Metro",R.drawable.metro,"Colegio","Colegio"));
        list.add(new Palabra("Multiplicación",R.drawable.multiplicacion,"Colegio","Colegio"));
        list.add(new Palabra("Número",R.drawable.numero,"Colegio","Colegio"));
        list.add(new Palabra("Palabra",R.drawable.palabra,"Colegio","Colegio"));
        list.add(new Palabra("Patio",R.drawable.patio,"Colegio","Colegio"));
        list.add(new Palabra("Resta",R.drawable.resta,"Colegio","Colegio"));
        list.add(new Palabra("Servicio",R.drawable.servicio,"Colegio","Colegio"));
        list.add(new Palabra("Suma",R.drawable.suma,"Colegio","Colegio"));

        list.add(new Palabra("Amarillo",R.drawable.amarillo,"Colegio","Colores"));
        list.add(new Palabra("Azul",R.drawable.azul,"Colegio","Colores"));
        list.add(new Palabra("Blanco",R.drawable.blanco,"Colegio","Colores"));
        list.add(new Palabra("Colores",R.drawable.colores,"Colegio","Colores"));
        list.add(new Palabra("Marrón",R.drawable.marron,"Colegio","Colores"));
        list.add(new Palabra("Naranja",R.drawable.naranja,"Colegio","Colores"));
        list.add(new Palabra("Negro",R.drawable.negro,"Colegio","Colores"));
        list.add(new Palabra("Rojo",R.drawable.rojo,"Colegio","Colores"));
        list.add(new Palabra("Rosa",R.drawable.rosa,"Colegio","Colores"));
        list.add(new Palabra("Verde",R.drawable.verde,"Colegio","Colores"));

        list.add(new Palabra("Bolígrafo",R.drawable.boligrafo,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Borrador",R.drawable.borrador,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Cera",R.drawable.cera,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Cosas del colegio",R.drawable.cosas_del_colegio,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Cosas",R.drawable.cosas,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Cuaderno",R.drawable.cuaderno,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Cuento",R.drawable.cuento,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Diccionario",R.drawable.diccionario,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Goma",R.drawable.goma,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Hoja",R.drawable.hoja,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Lápices de colores",R.drawable.lapices_de_colores,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Lápiz",R.drawable.lapiz,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Libro",R.drawable.libro,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Papel",R.drawable.papel,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Papelera",R.drawable.papelera,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Pegamento",R.drawable.pegamento,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Pintura",R.drawable.pintura,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Pizarra",R.drawable.pizarra,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Plastilina",R.drawable.plastilina,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Rotulador",R.drawable.rotulador,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Sacapuntas",R.drawable.sacapuntas,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Tijeras",R.drawable.tijeras,"Colegio","CosasDelColegio"));
        list.add(new Palabra("Tiza",R.drawable.tiza,"Colegio","CosasDelColegio"));

        list.add(new Palabra("Círculo",R.drawable.circulo,"Colegio","FormasYTamaños"));
        list.add(new Palabra("Cuadrado",R.drawable.cuadrado,"Colegio","FormasYTamaños"));
        list.add(new Palabra("Formas y Tamaños",R.drawable.formas_y_tamanos,"Colegio","FormasYTamaños"));
        list.add(new Palabra("Formas",R.drawable.formas,"Colegio","FormasYTamaños"));
        list.add(new Palabra("Grande",R.drawable.grande,"Colegio","FormasYTamaños"));
        list.add(new Palabra("Mediano",R.drawable.mediano,"Colegio","FormasYTamaños"));
        list.add(new Palabra("Pequeño",R.drawable.pequeno,"Colegio","FormasYTamaños"));
        list.add(new Palabra("Tamaño",R.drawable.tamano,"Colegio","FormasYTamaños"));

        list.add(new Palabra("Aceite",R.drawable.aceite,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Alimento",R.drawable.alimento,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Arroz",R.drawable.arroz,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Azucar",R.drawable.azucar,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Bebida",R.drawable.bebida,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Bocadillo",R.drawable.bocadillo,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Caramelo",R.drawable.caramelo,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Carnes",R.drawable.carnes,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Cebolla",R.drawable.cebolla,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Cena",R.drawable.cena,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Chocolate",R.drawable.chocolate,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Comida",R.drawable.comida,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Desayuno",R.drawable.desayuno,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Galleta",R.drawable.galleta,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Huevo",R.drawable.huevo,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Leche",R.drawable.leche,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Lechuga",R.drawable.lechuga,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Limón",R.drawable.limon,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Macarrones",R.drawable.macarrones,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Merienda",R.drawable.merienda,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Pan",R.drawable.pan,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Patata",R.drawable.patata,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Pescado",R.drawable.pescado,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Pollo",R.drawable.pollo,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Puré",R.drawable.pure,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Queso",R.drawable.queso,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Sal",R.drawable.sal,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Sed",R.drawable.sed,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Sopa",R.drawable.sopa,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Tomate",R.drawable.tomate,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Zanahoria",R.drawable.zanahoria,"Comidas Y Bebidas","Comidas Y Bebidas"));
        list.add(new Palabra("Zumo",R.drawable.zumo,"Comidas Y Bebidas","Comidas Y Bebidas"));

        list.add(new Palabra("Flan",R.drawable.flan,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Fresa",R.drawable.fresa,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Fruta",R.drawable.fruta,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Helado",R.drawable.helado,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Manzana",R.drawable.manzana,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Naranja",R.drawable.naranja,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Pera",R.drawable.pera,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Platano",R.drawable.platano,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Postre",R.drawable.postre,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Sandía",R.drawable.sandia,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Tarta",R.drawable.tarta,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Uva",R.drawable.uva,"Comidas Y Bebidas","Postres"));
        list.add(new Palabra("Yogur",R.drawable.yogur,"Comidas Y Bebidas","Postres"));

        list.add(new Palabra("Abuelo",R.drawable.abuelo,"Familia","Familia"));
        list.add(new Palabra("Amigo",R.drawable.amigo,"Familia","Familia"));
        list.add(new Palabra("Bebé",R.drawable.bebe,"Familia","Familia"));
        list.add(new Palabra("Ciego",R.drawable.ciego,"Familia","Familia"));
        list.add(new Palabra("Familia",R.drawable.familia,"Familia","Familia"));
        list.add(new Palabra("Hermano",R.drawable.hermano,"Familia","Familia"));
        list.add(new Palabra("Mamá",R.drawable.mama,"Familia","Familia"));
        list.add(new Palabra("Niña",R.drawable.nina,"Familia","Familia"));
        list.add(new Palabra("Niño",R.drawable.nino,"Familia","Familia"));
        list.add(new Palabra("Papá",R.drawable.papa,"Familia","Familia"));
        list.add(new Palabra("Persona",R.drawable.persona,"Familia","Familia"));
        list.add(new Palabra("Primo",R.drawable.primo,"Familia","Familia"));
        list.add(new Palabra("Sordo",R.drawable.sordo,"Familia","Familia"));
        list.add(new Palabra("Sordo ciego",R.drawable.sordociego,"Familia","Familia"));
        list.add(new Palabra("Tío",R.drawable.tio,"Familia","Familia"));

        list.add(new Palabra("Abeja",R.drawable.abeja,"Naturaleza","Animales"));
        list.add(new Palabra("Águila",R.drawable.aguila,"Naturaleza","Animales"));
        list.add(new Palabra("Animal",R.drawable.animal,"Naturaleza","Animales"));
        list.add(new Palabra("Ballena",R.drawable.ballena,"Naturaleza","Animales"));
        list.add(new Palabra("Burro",R.drawable.burro,"Naturaleza","Animales"));
        list.add(new Palabra("Caballo",R.drawable.caballo,"Naturaleza","Animales"));
        list.add(new Palabra("Cabra",R.drawable.cabra,"Naturaleza","Animales"));
        list.add(new Palabra("Camello",R.drawable.camello,"Naturaleza","Animales"));
        list.add(new Palabra("Cerdo",R.drawable.cerdo,"Naturaleza","Animales"));
        list.add(new Palabra("Cocodrilo",R.drawable.cocodrilo,"Naturaleza","Animales"));
        list.add(new Palabra("Conejo",R.drawable.conejo,"Naturaleza","Animales"));
        list.add(new Palabra("Delfín",R.drawable.delfin,"Naturaleza","Animales"));
        list.add(new Palabra("Elefante",R.drawable.elefante,"Naturaleza","Animales"));
        list.add(new Palabra("Foca",R.drawable.foca,"Naturaleza","Animales"));
        list.add(new Palabra("Gallina",R.drawable.gallina,"Naturaleza","Animales"));
        list.add(new Palabra("Gato",R.drawable.gato,"Naturaleza","Animales"));
        list.add(new Palabra("Granja",R.drawable.granja,"Naturaleza","Animales"));
        list.add(new Palabra("Jirafa",R.drawable.jirafa,"Naturaleza","Animales"));
        list.add(new Palabra("León",R.drawable.leon,"Naturaleza","Animales"));
        list.add(new Palabra("Loro",R.drawable.loro,"Naturaleza","Animales"));
        list.add(new Palabra("Mariposa",R.drawable.mariposa,"Naturaleza","Animales"));
        list.add(new Palabra("Mono",R.drawable.mono,"Naturaleza","Animales"));

        list.add(new Palabra("Abeto",R.drawable.abeto,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Árbol",R.drawable.arbol,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Arcoíris",R.drawable.arco_iris,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Arena",R.drawable.arena,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Estrella",R.drawable.estrella,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Faro",R.drawable.faro,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Flor",R.drawable.flor,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Flotador",R.drawable.flotador,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Fuego",R.drawable.fuego,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Hierba",R.drawable.hierba,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Hoja",R.drawable.hoja,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Lago",R.drawable.lago,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Luna",R.drawable.luna,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Mar",R.drawable.mar,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Margarita",R.drawable.margarita,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Montaña",R.drawable.montana,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Naturaleza",R.drawable.naturaleza,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Palmera",R.drawable.palmera,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Piedra",R.drawable.piedra,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Playa",R.drawable.playa,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Pozo",R.drawable.pozo,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Río",R.drawable.rio,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Saco de dormir",R.drawable.saco_de_dormir,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Sombrilla",R.drawable.sombrilla,"Naturaleza","Naturaleza"));
        list.add(new Palabra("Tienda de campaña",R.drawable.tienda_campana,"Naturaleza","Naturaleza"));

        list.add(new Palabra("Calor",R.drawable.calor,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Frío",R.drawable.frio,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Lluvia",R.drawable.lluvia,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Nieve",R.drawable.nieve,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Nube",R.drawable.nube,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Nublado",R.drawable.nublado,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Sol",R.drawable.sol,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Tiempo atmosfético",R.drawable.tiempo_atmosferico,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Tormenta",R.drawable.tormenta,"Naturaleza","TiempoAtmosferico"));
        list.add(new Palabra("Viento",R.drawable.viento,"Naturaleza","TiempoAtmosferico"));

        list.add(new Palabra("Día de la semana",R.drawable.dia_de_la_semana,"Calendario","Semana"));
        list.add(new Palabra("Día",R.drawable.dia_manana,"Calendario","Semana"));
        list.add(new Palabra("Domingo",R.drawable.domingo,"Calendario","Semana"));
        list.add(new Palabra("Fin de semana",R.drawable.fin_de_semana,"Calendario","Semana"));
        list.add(new Palabra("Jueves",R.drawable.jueves,"Calendario","Semana"));
        list.add(new Palabra("Martes",R.drawable.martes,"Calendario","Semana"));
        list.add(new Palabra("Miercoles",R.drawable.miercoles,"Calendario","Semana"));
        list.add(new Palabra("Sabado",R.drawable.sabado,"Calendario","Semana"));
        list.add(new Palabra("Semana",R.drawable.semana,"Calendario","Semana"));
        list.add(new Palabra("Viernes",R.drawable.viernes,"Calendario","Semana"));

        list.add(new Palabra("Cumpleaños",R.drawable.cumpleanos,"Calendario","Fiestas"));
        list.add(new Palabra("Fiesta",R.drawable.fiesta,"Calendario","Fiestas"));
        list.add(new Palabra("Navidad",R.drawable.navidad,"Calendario","Fiestas"));
        list.add(new Palabra("Papa Noel",R.drawable.papa_noel,"Calendario","Fiestas"));
        list.add(new Palabra("Reyes Magos",R.drawable.reyes_magos,"Calendario","Fiestas"));

        list.add(new Palabra("Enero",R.drawable.enero,"Calendario","Meses"));
        list.add(new Palabra("Febrero",R.drawable.febrero,"Calendario","Meses"));
        list.add(new Palabra("Marzo",R.drawable.marzo,"Calendario","Meses"));
        list.add(new Palabra("Abril",R.drawable.abril,"Calendario","Meses"));
        list.add(new Palabra("Mayo",R.drawable.mayo,"Calendario","Meses"));
        list.add(new Palabra("Junio",R.drawable.junio,"Calendario","Meses"));
        list.add(new Palabra("Julio",R.drawable.julio,"Calendario","Meses"));
        list.add(new Palabra("Agosto",R.drawable.agosto,"Calendario","Meses"));
        list.add(new Palabra("Septiembre",R.drawable.septiembre,"Calendario","Meses"));
        list.add(new Palabra("Octubre",R.drawable.octubre,"Calendario","Meses"));
        list.add(new Palabra("Noviembre",R.drawable.noviembre,"Calendario","Meses"));
        list.add(new Palabra("Diciembre",R.drawable.diciembre,"Calendario","Meses"));
        list.add(new Palabra("Mes del año",R.drawable.meses_del_ano,"Calendario","Meses"));
        list.add(new Palabra("Mes",R.drawable.mes,"Calendario","Meses"));
        list.add(new Palabra("Año",R.drawable.ano,"Calendario","Meses"));
        list.add(new Palabra("Calendario",R.drawable.calendario,"Calendario","Meses"));

        list.add(new Palabra("Ayer",R.drawable.ayer,"Calendario","Tiempo"));
        list.add(new Palabra("En punto",R.drawable.en_punto,"Calendario","Tiempo"));
        list.add(new Palabra("¿Que hora es?",R.drawable.hora_interrogativa,"Calendario","Tiempo"));
        list.add(new Palabra("Hoy",R.drawable.hoy,"Calendario","Tiempo"));
        list.add(new Palabra("La hora de",R.drawable.la_hora_de,"Calendario","Tiempo"));
        list.add(new Palabra("Mañana",R.drawable.manana,"Calendario","Tiempo"));
        list.add(new Palabra("Menos cuarto",R.drawable.menos_cuarto,"Calendario","Tiempo"));
        list.add(new Palabra("Por la mañana",R.drawable.por_la_manana,"Calendario","Tiempo"));
        list.add(new Palabra("Por la noche",R.drawable.por_la_noche,"Calendario","Tiempo"));
        list.add(new Palabra("Por la tarde",R.drawable.por_la_tarde,"Calendario","Tiempo"));
        list.add(new Palabra("Tiempo",R.drawable.tiempo,"Calendario","Tiempo"));
        list.add(new Palabra("Y cuarto",R.drawable.y_cuarto,"Calendario","Tiempo"));
        list.add(new Palabra("Y media",R.drawable.y_media,"Calendario","Tiempo"));

        list.add(new Palabra("Estaciones",R.drawable.estaciones,"Calendario","Estaciones"));
        list.add(new Palabra("Invierno",R.drawable.invierno,"Calendario","Estaciones"));
        list.add(new Palabra("Otoño",R.drawable.otono,"Calendario","Estaciones"));
        list.add(new Palabra("Primavera",R.drawable.primavera,"Calendario","Estaciones"));
        list.add(new Palabra("Verano",R.drawable.verano,"Calendario","Estaciones"));

        list.add(new Palabra("Boca",R.drawable.boca,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Brazo",R.drawable.brazo,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Cabeza",R.drawable.cabeza,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Cuerpo",R.drawable.cuerpo,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Culo",R.drawable.culo,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Dedo",R.drawable.dedo,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Dientes",R.drawable.dientes,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Lengua",R.drawable.lengua,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Mano",R.drawable.mano,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Nariz",R.drawable.nariz,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Ojo",R.drawable.ojo,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Oreja",R.drawable.oreja,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Pelo",R.drawable.pelo,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Pene",R.drawable.pene,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Pie",R.drawable.pie,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Pierna",R.drawable.pierna,"Cuerpo","Cuerpo"));
        list.add(new Palabra("Vulva",R.drawable.vulva,"Cuerpo","Cuerpo"));

        list.add(new Palabra("Sentidos",R.drawable.sentidos,"Cuerpo","Sentido"));
        list.add(new Palabra("Gusto",R.drawable.gusto,"Cuerpo","Sentido"));
        list.add(new Palabra("Oido",R.drawable.oido,"Cuerpo","Sentido"));
        list.add(new Palabra("Olfato",R.drawable.olfato,"Cuerpo","Sentido"));
        list.add(new Palabra("Tacto",R.drawable.tacto,"Cuerpo","Sentido"));
        list.add(new Palabra("Vista",R.drawable.vista,"Cuerpo","Sentido"));

        list.add(new Palabra("Abrigo",R.drawable.abrigo,"Ropa","Ropa"));
        list.add(new Palabra("Bañador chica",R.drawable.banador_chica,"Ropa","Ropa"));
        list.add(new Palabra("Bañador chico",R.drawable.banador_chico,"Ropa","Ropa"));
        list.add(new Palabra("Braga",R.drawable.braga,"Ropa","Ropa"));
        list.add(new Palabra("Bufanda",R.drawable.bufanda,"Ropa","Ropa"));
        list.add(new Palabra("Calzoncillo",R.drawable.calzoncillo,"Ropa","Ropa"));
        list.add(new Palabra("Camisa",R.drawable.camisa,"Ropa","Ropa"));
        list.add(new Palabra("Chandal",R.drawable.chandal,"Ropa","Ropa"));
        list.add(new Palabra("Gafas",R.drawable.gafas,"Ropa","Ropa"));
        list.add(new Palabra("Gorra",R.drawable.gorra,"Ropa","Ropa"));
        list.add(new Palabra("Jersey",R.drawable.jersey,"Ropa","Ropa"));
        list.add(new Palabra("Mochila",R.drawable.mochila,"Ropa","Ropa"));
        list.add(new Palabra("Pantalon",R.drawable.pantalon,"Ropa","Ropa"));
        list.add(new Palabra("Pijama",R.drawable.pijama,"Ropa","Ropa"));
        list.add(new Palabra("Reloj",R.drawable.reloj,"Ropa","Ropa"));
        list.add(new Palabra("Ropa",R.drawable.ropa,"Ropa","Ropa"));
        list.add(new Palabra("Zapatilla",R.drawable.zapatilla,"Ropa","Ropa"));
        list.add(new Palabra("Zapato",R.drawable.zapato,"Ropa","Ropa"));

        list.add(new Palabra("Como",R.drawable.como,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Como se signa",R.drawable.como_se_signa,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Cual",R.drawable.cual,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Cuando (pasado)",R.drawable.cuando_pasado,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Cuanto",R.drawable.cuanto,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Donde",R.drawable.donde,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Para que",R.drawable.para,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Preguntas",R.drawable.preguntas,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Que",R.drawable.que,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Que dia es",R.drawable.que_dia_es,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Que dice",R.drawable.que_dice,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Que tal",R.drawable.que_tal,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Quien",R.drawable.quien,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Si o no",R.drawable.si_o_no,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Como se dice",R.drawable.como_se_dice,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Cuando (presente y futuro)",R.drawable.cuando_presente_y_futuro,"Saludos y preguntas","Preguntas"));
        list.add(new Palabra("Por que",R.drawable.por,"Saludos y preguntas","Preguntas"));

        list.add(new Palabra("Adion",R.drawable.adios,"Saludos y preguntas","Saludos"));
        list.add(new Palabra("Buenas noches",R.drawable.buenas_noches,"Saludos y preguntas","Saludos"));
        list.add(new Palabra("Buenas tardes",R.drawable.buenas_tardes,"Saludos y preguntas","Saludos"));
        list.add(new Palabra("Buenos dias",R.drawable.buenos_dias,"Saludos y preguntas","Saludos"));
        list.add(new Palabra("Cortesia",R.drawable.cortesia,"Saludos y preguntas","Saludos"));
        list.add(new Palabra("Cuidado",R.drawable.cuidado,"Saludos y preguntas","Saludos"));
        list.add(new Palabra("De nada",R.drawable.de_nada,"Saludos y preguntas","Saludos"));
        list.add(new Palabra("Gracias",R.drawable.gracias,"Saludos y preguntas","Saludos"));
        list.add(new Palabra("Hola",R.drawable.hola,"Saludos y preguntas","Saludos"));
        list.add(new Palabra("No",R.drawable.no,"Saludos y preguntas","Saludos"));
        list.add(new Palabra("Nombre",R.drawable.nombre,"Saludos y preguntas","Saludos"));
        list.add(new Palabra("Por favor",R.drawable.por_favor,"Saludos y preguntas","Saludos"));
        list.add(new Palabra("Saludo",R.drawable.saludo,"Saludos y preguntas","Saludos"));
        list.add(new Palabra("Si",R.drawable.si,"Saludos y preguntas","Saludos"));
        list.add(new Palabra("Signo",R.drawable.signo,"Saludos y preguntas","Saludos"));

        list.add(new Palabra("Ayudar",R.drawable.ayudar,"Gramatica","Verbos"));
        list.add(new Palabra("Comprar",R.drawable.comprar,"Gramatica","Verbos"));
        list.add(new Palabra("Cortar",R.drawable.cortar,"Gramatica","Verbos"));
        list.add(new Palabra("Crecer (Planta)",R.drawable.crecer_planta,"Gramatica","Verbos"));
        list.add(new Palabra("Abrazar",R.drawable.abrazar,"Gramatica","Verbos"));
        list.add(new Palabra("Amar",R.drawable.amar,"Gramatica","Verbos"));
        list.add(new Palabra("Andar",R.drawable.andar,"Gramatica","Verbos"));
        list.add(new Palabra("Aprender",R.drawable.aprender,"Gramatica","Verbos"));
        list.add(new Palabra("Beber",R.drawable.beber,"Gramatica","Verbos"));
        list.add(new Palabra("Besar",R.drawable.besar,"Gramatica","Verbos"));
        list.add(new Palabra("Comer",R.drawable.comer,"Gramatica","Verbos"));
        list.add(new Palabra("Conocer",R.drawable.conocer,"Gramatica","Verbos"));
        list.add(new Palabra("Contar",R.drawable.contar,"Gramatica","Verbos"));
        list.add(new Palabra("Correr",R.drawable.correr,"Gramatica","Verbos"));
        list.add(new Palabra("Crecer",R.drawable.crecer,"Gramatica","Verbos"));
        list.add(new Palabra("Descansar",R.drawable.descansar,"Gramatica","Verbos"));
        list.add(new Palabra("Dormir",R.drawable.dormir,"Gramatica","Verbos"));
        list.add(new Palabra("Ducharse",R.drawable.ducharse,"Gramatica","Verbos"));
        list.add(new Palabra("Entender",R.drawable.entender,"Gramatica","Verbos"));
        list.add(new Palabra("Escribir",R.drawable.escribir,"Gramatica","Verbos"));
        list.add(new Palabra("Esperar",R.drawable.esperar,"Gramatica","Verbos"));
        list.add(new Palabra("Explicar",R.drawable.explicar,"Gramatica","Verbos"));
        list.add(new Palabra("Gritar",R.drawable.gritar,"Gramatica","Verbos"));
        list.add(new Palabra("Gustar",R.drawable.gustar,"Gramatica","Verbos"));
        list.add(new Palabra("Hablar Ise",R.drawable.hablar,"Gramatica","Verbos"));
        list.add(new Palabra("Jugar",R.drawable.jugar,"Gramatica","Verbos"));
        list.add(new Palabra("Lavar la cabeza",R.drawable.lavar_la_cabeza,"Gramatica","Verbos"));
        list.add(new Palabra("Leer",R.drawable.leer,"Gramatica","Verbos"));
        list.add(new Palabra("Llorar",R.drawable.llorar,"Gramatica","Verbos"));
        list.add(new Palabra("Montar",R.drawable.montar,"Gramatica","Verbos"));
        list.add(new Palabra("No conocer",R.drawable.no_conocer,"Gramatica","Verbos"));
        list.add(new Palabra("No tener",R.drawable.no_tener,"Gramatica","Verbos"));
        list.add(new Palabra("Pegar",R.drawable.pegar,"Gramatica","Verbos"));
        list.add(new Palabra("Saborear",R.drawable.saborear,"Gramatica","Verbos"));
        list.add(new Palabra("Verbo",R.drawable.verbo,"Gramatica","Verbos"));
        list.add(new Palabra("Vestirse",R.drawable.vestirse,"Gramatica","Verbos"));
        list.add(new Palabra("Hablar (oral)",R.drawable.hablar_oral,"Gramatica","Verbos"));
        list.add(new Palabra("Lavar la ropa",R.drawable.lavar_la_ropa,"Gramatica","Verbos"));
        list.add(new Palabra("Lavar los dientes",R.drawable.lavar_los_dientes,"Gramatica","Verbos"));
        list.add(new Palabra("Levantarse",R.drawable.levantarse,"Gramatica","Verbos"));
        list.add(new Palabra("Nacer",R.drawable.nacer,"Gramatica","Verbos"));
        list.add(new Palabra("No gustar",R.drawable.no_gustar,"Gramatica","Verbos"));
        list.add(new Palabra("Oir",R.drawable.oir,"Gramatica","Verbos"));
        list.add(new Palabra("Oler",R.drawable.oler,"Gramatica","Verbos"));
        list.add(new Palabra("Pasear",R.drawable.pasear,"Gramatica","Verbos"));
        list.add(new Palabra("Patinar",R.drawable.patinar,"Gramatica","Verbos"));
        list.add(new Palabra("Peinarse",R.drawable.peinarse,"Gramatica","Verbos"));
        list.add(new Palabra("Ponerse",R.drawable.ponerse,"Gramatica","Verbos"));
        list.add(new Palabra("Quitarse",R.drawable.quitarse,"Gramatica","Verbos"));
        list.add(new Palabra("Regalar",R.drawable.regalar,"Gramatica","Verbos"));
        list.add(new Palabra("Reir",R.drawable.reir,"Gramatica","Verbos"));
        list.add(new Palabra("Saltar",R.drawable.saltar,"Gramatica","Verbos"));
        list.add(new Palabra("Sentarse",R.drawable.sentarse,"Gramatica","Verbos"));
        list.add(new Palabra("Tener",R.drawable.tener,"Gramatica","Verbos"));
        list.add(new Palabra("Tocar",R.drawable.tocar,"Gramatica","Verbos"));
        list.add(new Palabra("Vamos a",R.drawable.vamos_a,"Gramatica","Verbos"));
        list.add(new Palabra("Ver",R.drawable.ver,"Gramatica","Verbos"));
        list.add(new Palabra("Vivir",R.drawable.vivir,"Gramatica","Verbos"));

        list.add(new Palabra("Abajo",R.drawable.abajo,"Gramatica","Adverbios"));
        list.add(new Palabra("Adverbio",R.drawable.adverbio,"Gramatica","Adverbios"));
        list.add(new Palabra("Bien",R.drawable.bien,"Gramatica","Adverbios"));
        list.add(new Palabra("Debajo",R.drawable.debajo,"Gramatica","Adverbios"));
        list.add(new Palabra("Dentro",R.drawable.dentro,"Gramatica","Adverbios"));
        list.add(new Palabra("Derecha",R.drawable.derecha,"Gramatica","Adverbios"));
        list.add(new Palabra("Detras",R.drawable.detras,"Gramatica","Adverbios"));
        list.add(new Palabra("Encima",R.drawable.encima,"Gramatica","Adverbios"));
        list.add(new Palabra("Izquierda",R.drawable.izquierda,"Gramatica","Adverbios"));
        list.add(new Palabra("Lejos",R.drawable.lejos,"Gramatica","Adverbios"));
        list.add(new Palabra("Mal",R.drawable.mal,"Gramatica","Adverbios"));
        list.add(new Palabra("Arriba",R.drawable.arriba,"Gramatica","Adverbios"));
        list.add(new Palabra("Cerca",R.drawable.cerca,"Gramatica","Adverbios"));
        list.add(new Palabra("Delante",R.drawable.delante,"Gramatica","Adverbios"));
        list.add(new Palabra("Fuera",R.drawable.fuera,"Gramatica","Adverbios"));

        return list;
    }
}
